[package]
name = "libreflow_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
byteorder = "1.5.0"
regex = "1.10.2"
serde = "1.0.193"
thiserror = "1.0.50"


